import { NextResponse } from 'next/server';
import prisma from '@/lib/prisma';

// Weekly discussion templates
const WEEKLY_TEMPLATES = [
  {
    type: 'WEEKLY_OVERRATED',
    title: "What's the most overrated MRR this week?",
    content: `Let's discuss! Share your thoughts on startups that might be valued higher than their fundamentals suggest.

**Rules:**
- Be respectful - critique ideas, not people
- Back up your opinion with reasoning
- This is for discussion, not attacking founders

What startup do you think is overrated this week and why?`,
    category: 'WEEKLY_DISCUSSION',
  },
  {
    type: 'WEEKLY_BOTTLENECK',
    title: "What's your biggest bottleneck going from $1K to $5K MRR?",
    content: `Share your struggles and help others overcome their challenges!

Common bottlenecks:
- Customer acquisition cost too high
- Churn rate issues
- Feature prioritization paralysis
- Time constraints (side project)

**What's holding YOU back?**`,
    category: 'REVENUE_GROWTH',
  },
  {
    type: 'WEEKLY_CHECKLIST',
    title: 'Pre-Sale Checklist: What should founders prepare?',
    content: `If you're considering selling your startup, what should you have ready?

Let's build a community checklist:
- [ ] Financial documentation
- [ ] Customer contracts/agreements
- [ ] Technical documentation
- [ ] Team transition plan

**What else would you add?**`,
    category: 'EXIT_STRATEGY',
  },
  {
    type: 'WEEKLY_MILESTONE',
    title: 'Share Your MRR Milestone This Week!',
    content: `Celebrate your wins! Share your MRR milestones, no matter how small.

Did you:
- Hit your first $100 MRR?
- Cross $1K MRR?
- Reach $10K MRR?
- Hit a new record?

**Share your journey and tips for others!**`,
    category: 'SHOW_TELL',
  },
  {
    type: 'WEEKLY_STRATEGY',
    title: 'What acquisition channel is working best for you?',
    content: `Let's share what's actually working for user acquisition.

Popular channels:
- SEO / Content Marketing
- Paid Ads (Google, Facebook, etc.)
- Product Hunt / Exitasy launches
- Cold outreach
- Partnerships
- Word of mouth

**What's your #1 channel and why?**`,
    category: 'REVENUE_GROWTH',
  },
];

// POST /api/forum/seed - Create weekly auto-generated threads
export async function POST(req: Request) {
  try {
    // Verify cron secret (for production security)
    const authHeader = req.headers.get('authorization');
    const cronSecret = process.env.CRON_SECRET;

    if (cronSecret && authHeader !== `Bearer ${cronSecret}`) {
      return NextResponse.json(
        { message: 'Unauthorized' },
        { status: 401 }
      );
    }

    const now = new Date();
    const weekStart = new Date(now);
    weekStart.setDate(weekStart.getDate() - weekStart.getDay()); // Start of current week
    weekStart.setHours(0, 0, 0, 0);

    // Check which templates haven't been created this week
    const existingThreads = await prisma.forumThread.findMany({
      where: {
        isAutoGenerated: true,
        createdAt: { gte: weekStart },
      },
      select: { templateType: true },
    });

    const existingTypes = new Set(existingThreads.map((t) => t.templateType));

    // Find templates that haven't been created this week
    const templatesToCreate = WEEKLY_TEMPLATES.filter(
      (t) => !existingTypes.has(t.type)
    );

    if (templatesToCreate.length === 0) {
      return NextResponse.json({
        message: 'All weekly threads already created',
        created: 0,
      });
    }

    // Create missing threads (pick one randomly per call for distributed creation)
    const randomTemplate = templatesToCreate[Math.floor(Math.random() * templatesToCreate.length)];

    const thread = await prisma.forumThread.create({
      data: {
        title: randomTemplate.title,
        content: randomTemplate.content,
        category: randomTemplate.category,
        isAutoGenerated: true,
        templateType: randomTemplate.type,
        isPinned: true, // Pin auto-generated threads
      },
    });

    return NextResponse.json({
      message: 'Weekly thread created',
      thread: {
        id: thread.id,
        title: thread.title,
        templateType: thread.templateType,
      },
      remainingTemplates: templatesToCreate.length - 1,
    });
  } catch (error) {
    console.error('Error seeding forum:', error);
    return NextResponse.json(
      { message: 'Internal server error' },
      { status: 500 }
    );
  }
}

// GET /api/forum/seed - Check seeding status
export async function GET() {
  try {
    const now = new Date();
    const weekStart = new Date(now);
    weekStart.setDate(weekStart.getDate() - weekStart.getDay());
    weekStart.setHours(0, 0, 0, 0);

    const existingThreads = await prisma.forumThread.findMany({
      where: {
        isAutoGenerated: true,
        createdAt: { gte: weekStart },
      },
      select: {
        id: true,
        title: true,
        templateType: true,
        createdAt: true,
        replyCount: true,
      },
    });

    const existingTypes = new Set(existingThreads.map((t) => t.templateType));
    const missingTypes = WEEKLY_TEMPLATES.filter(
      (t) => !existingTypes.has(t.type)
    ).map((t) => t.type);

    return NextResponse.json({
      weekStart: weekStart.toISOString(),
      created: existingThreads,
      missing: missingTypes,
      allCreated: missingTypes.length === 0,
    });
  } catch (error) {
    console.error('Error checking forum seed status:', error);
    return NextResponse.json(
      { message: 'Internal server error' },
      { status: 500 }
    );
  }
}
